version: '3.9'
services:
  forum_frontend:
    container_name: forum_frontend
    image: 'forum_frontend'
    build:
      context: ./client
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_API_BASE: ${REACT_APP_API_BASE}
        REACT_APP_GOOGLE_ID: ${GOOGLE_ID}
        REACT_APP_GITHUB_ID: ${GITHUB_ID}
    ports:
      - '3000:3000'
    # restart: always
    depends_on:
      - forum_backend

  forum_nginx_only:
    container_name: forum_nginx_only
    image: 'forum_nginx_only'
    build:
      context: ./client
      dockerfile: DockerfileNginxOnly
    ports:
      - '3000:3000'
    # restart: always

  forum_backend:
    container_name: forum_backend
    image: 'forum_backend'
    build:
      context: ./server
      args:
        NODE_ENV: ${NODE_ENV}
        POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PORT: ${PORT}
        FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
        JWT_KEY: ${JWT_KEY}
        GOOGLE_ID: ${GOOGLE_ID}
        GOOGLE_SECRET: ${GOOGLE_SECRET}
        GITHUB_ID: ${GITHUB_ID}
        GITHUB_SECRET: ${GITHUB_SECRET}
    ports:
      - '5000:5000'
    # restart: always
    depends_on:
      - forum_postgres

  forum_postgres:
    container_name: forum_postgres
    hostname: forum_postgres
    image: postgres:13.3
    env_file: .env
    volumes:
      - ../forum_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    # restart: always
