start:
	npm run start

env:
	cp -n .env.example .env || true

dev:
	npm run dev

lint:
	npm run lint

test:
	npm run test
	
migrate:
	npm run migrate
	
rollback:
	npm run rollback
	
seed:
	npm run seed
	